branch-defaults:
  default:
    environment: Portfolio-env
environment-defaults:
  Portfolio-env:
    branch: null
    repository: null
global:
  application_name: portfolio
  default_ec2_keyname: portkey
  default_platform: .NET 9 running on 64bit Amazon Linux 2023
  default_region: us-east-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: null
  workspace_type: Application
